#!/bin/bash

# Define a list of packages to install
packages=("package1" "package2" "package3")

# Update package list and install packages
sudo apt update
sudo apt install "${packages[@]}"

echo "Software installation completed."
